# Generated by Django 3.1.7 on 2021-03-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BudgetRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.TextField()),
                ("birth_date", models.TextField()),
                ("description", models.TextField()),
                ("body_part", models.TextField()),
                ("sizeInCm", models.FloatField()),
                ("phone", models.TextField()),
                ("userAlias", models.TextField()),
            ],
        ),
    ]
