# Generated by Django 3.1.7 on 2021-03-29 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgetrequest", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budgetrequest",
            old_name="sizeInCm",
            new_name="size_in_cm",
        ),
        migrations.RenameField(
            model_name="budgetrequest",
            old_name="userAlias",
            new_name="user_alias",
        ),
    ]
